### ISSUE TITLE
Stablize Windows version of binary

### ISSUE THREAD

**Issue by ArmandMeppa** [ADORSYS-GIS/wazuh-agent-status#7]
- [ ] Icon not displayed on Windows
- [ ] Error message displayed for a working function

**Comment by ArmandMeppa** [comment]
Documenting on the 2nd issue https://github.com/getlantern/systray/issues/148 and looking for a work-around

**Comment by ArmandMeppa** [comment]
WIP

**Comment by yannicksiewe** [comment]
Duplicate
